trigger:
- develop
- master
- release/*
- hotfix/*

pr:
- develop
- release/*
- hotfix/*

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2022'
  steps:
  # .NET 5 required for GitVersion
  - task: UseDotNet@2
    inputs:
      version: '5.x'
    displayName: 'Install .NET 5'
  - task: UseDotNet@2
    inputs:
      version: '6.x'
    displayName: 'Install .NET 6'
  - task: UseDotNet@2
    inputs:
      version: '7.x'
    displayName: 'Install .NET 7'
  - task: UseDotNet@2
    inputs:
      version: '8.x'
    displayName: 'Install .NET 8'
  - powershell: ./build.ps1
    displayName: 'Cake Build'