trigger:
- develop
- master
- release/*
- hotfix/*

pr:
- develop
- release/*
- hotfix/*

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2022'
  steps:
  - powershell: ./build.ps1
    displayName: 'Cake Build'